CREATE PROFILE auth_profile LIMIT
    PASSWORD_LIFE_TIME UNLIMITED
    PASSWORD_GRACE_TIME 7
    PASSWORD_REUSE_TIME 365
    PASSWORD_REUSE_MAX 5
    FAILED_LOGIN_ATTEMPTS UNLIMITED
    PASSWORD_LOCK_TIME 1
    PASSWORD_VERIFY_FUNCTION NULL;

ALTER USER auth_schema PROFILE auth_profile;


CREATE PROFILE user_profile LIMIT
    PASSWORD_LIFE_TIME UNLIMITED
    PASSWORD_GRACE_TIME 7
    PASSWORD_REUSE_TIME 365
    PASSWORD_REUSE_MAX 10
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LOCK_TIME 0.03--30  минут
    PASSWORD_VERIFY_FUNCTION NULL;

ALTER USER user_schema PROFILE user_profile;


CREATE PROFILE moderator_profile LIMIT
    PASSWORD_LIFE_TIME UNLIMITED
    PASSWORD_GRACE_TIME 5
    PASSWORD_REUSE_TIME 365
    PASSWORD_REUSE_MAX 12
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 1
    PASSWORD_VERIFY_FUNCTION NULL;

ALTER USER moderator_schema PROFILE moderator_profile;


CREATE PROFILE admin_profile LIMIT
    PASSWORD_LIFE_TIME UNLIMITED
    PASSWORD_GRACE_TIME 3
    PASSWORD_REUSE_TIME 365
    PASSWORD_REUSE_MAX 15
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 1
    PASSWORD_VERIFY_FUNCTION NULL;

ALTER USER admin_schema PROFILE admin_profile;